[streammon]
# working_directory: Where downloaded Twitch streams are saved.
# Use relative paths (from current directory) or absolute paths.
# Examples:
#   - "download_twitch"              (current directory)
#   - "../downloads/twitch"          (parent directory)
#   - "../../streams/archive"        (two levels up)
working_directory = "download_twitch"

# Arguments passed to twitch-dlp. (See https://github.com/DmitryScaletta/twitch-dlp)
# You can comment out lines using '#' to disable specific flags.
args = [
    "--live-from-start",
    "--retry-streams", "60",
    "--output", "[%(upload_date)s] [%(id)s] [%(uploader)s] [%(title)s].%(ext)s"
]

[scraper]
poll_interval = "120s"

# ========================== Channels ========================== #
# Common filter presets (Copy-paste these into channel filters)
# All: [".*"]
# Common keywords for yabai streams: ["(?i).*karaoke.*|.*archive.*|.*guerilla.*|.*gorilla.*|.*gorila.*|.*surprise.*|.*handcam.*|.*asmr.*"]

# Example:
# [[channel]]
# id = "sayasairroxs"
# name = "Saya Sairroxs"
# filters = [".*"]

# ===================== Phase ===================== #
# =============== Origins =============== #
[[channel]]
id = "asheliarinkou"
name = "Ashelia Rinkou"
filters = [".*"]

[[channel]]
id = "utatanenasa"
name = "Utatane Nasa"
filters = [".*"]

[[channel]]
id = "iorihakushika"
name = "Iori Hakushika"
filters = [".*"]

[[channel]]
id = "fujikurauruka"
name = "Fujikura Uruka"
filters = [".*"]

[[channel]]
id = "michiru_shisui"
name = "Michiru Shisui"
filters = [".*"]

# [[channel]]
# id = "tenma"
# name = "Tenma Maemi"
# filters = [".*"]

[[channel]]
id = "pippa"
name = "Pipkin Pippa"
filters = [".*"]

# =============== Invaders =============== #
# [[channel]]
# id = "kanekolumi"
# name = "Kaneko Lumi"
# filters = [".*"]

[[channel]]
id = "dizzydokuro"
name = "Dizzy Dokuro"
filters = [".*"]

[[channel]]
id = "jellyhoshiumi"
name = "Jelly Hoshiumi"
filters = [".*"]

[[channel]]
id = "emberamane"
name = "Ember Amane"
filters = [".*"]

# =============== Alias =============== #
[[channel]]
id = "remilianephys"
name = "Remilia Nephys"
filters = [".*"]

[[channel]]
id = "chisakaairi"
name = "Chisaka Airi"
filters = [".*"]

[[channel]]
id = "amanogawashiina"
name = "Amanogawa Shiina"
filters = [".*"]

[[channel]]
id = "himemiyarie"
name = "Himemiya Rie"
filters = [".*"]

[[channel]]
id = "erinamakina"
name = "Erina Makina"
filters = [".*"]

[[channel]]
id = "komachipanko"
name = "Komachi Panko"
filters = [".*"]

# =============== Euphoria =============== #
# [[channel]]
# id = "runieruse"
# name = "Runie Ruse"
# filters = [".*"]

[[channel]]
id = "eimiisami"
name = "Eimi Isami"
filters = [".*"]

[[channel]]
id = "muumuyu"
name = "Muu Muyu"
filters = [".*"]

[[channel]]
id = "hikanarihina"
name = "Hikanari Hina"
filters = [".*"]

# [[channel]]
# id = "sayasairroxs"
# name = "Saya Sairroxs"
# filters = [".*"]

# =============== Kaleido =============== #
[[channel]]
id = "kokoromomemory"
name = "Kokoromo Memory"
filters = [".*"]

[[channel]]
id = "grampico"
name = "Gram Pico"
filters = [".*"]

[[channel]]
id = "ayaseyuu_"
name = "Ayase Yuu"
filters = [".*"]

[[channel]]
id = "kaminariclara"
name = "Kaminari Clara"
filters = [".*"]

# ================ Quest ================ #
[[channel]]
id = "clioaite"
name = "Clio Aite"
filters = [".*"]

# ===================== Indies / Other ===================== #
[[channel]]
id = "chikafujilisa"
name = "Chikafuji Lisa"
filters = [".*"]